// File generated by `flutterfire configure` - DO NOT EDIT MANUALLY
// This file will be auto-generated with your Firebase project configuration

// Run this command to configure Firebase:
// flutterfire configure --project=YOUR_PROJECT_ID

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform, kIsWeb;

class DefaultFirebaseOptions {

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM_SoVsGqXYsH1R5dsYXbDbdu4lwSc678',
    appId: '1:487564182494:web:1ff3046c014e6d595e934f',
    messagingSenderId: '487564182494',
    projectId: 'flutterproject-b95b2',
    authDomain: 'flutterproject-b95b2.firebaseapp.com',
    storageBucket: 'flutterproject-b95b2.firebasestorage.app',
    measurementId: 'G-S31J83T2XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnQAv6TWX3MkLVsexOeMkFjHBJrsUQLY8',
    appId: '1:487564182494:android:febfb0186f1a1a805e934f',
    messagingSenderId: '487564182494',
    projectId: 'flutterproject-b95b2',
    storageBucket: 'flutterproject-b95b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOsL5z8pB8rVWuCogZHSIJCVrDhAk_gaE',
    appId: '1:487564182494:ios:11074ad0b19c347f5e934f',
    messagingSenderId: '487564182494',
    projectId: 'flutterproject-b95b2',
    storageBucket: 'flutterproject-b95b2.firebasestorage.app',
    iosBundleId: 'com.example.livevibe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'livevibe-project',
    databaseURL: 'https://livevibe-project.firebaseio.com',
    storageBucket: 'livevibe-project.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'livevibe-project',
    databaseURL: 'https://livevibe-project.firebaseio.com',
    storageBucket: 'livevibe-project.appspot.com',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}